### ISSUE TITLE
circular references, resulting in objects leak

### ISSUE THREAD

**Issue by chgz** [thinkgos/timer#6]
i found two situations where circular references exist， resulting in objects leak
1.  task and taskEntity reference each other.    
     if not exec Cancel()， it will not be GC
2. using the task object itself in its JobFunc

**Comment by thinkgos** [comment]
Go's GC not use Automatic Reference Counting, it use tracing garbage collection. No problem.

**Comment by thinkgos** [comment]
@chgz you can run `_examples/monitor/main.go` from a month, it start a pprof http  server.

**Comment by chgz** [comment]
first, this way, the object cannot be GCed, and it is easy to make mistakes.

```	
        task.WithJobFunc(func() {
		log.Println("job is executed. ", task)
	})
```
When I tested it,  observed through runtime.SetFinalizer. it was indeed not released.

the task will be released only if these two conditions are met: 
1. task.cancel is called by actively
2. the closure cannot use its own object

confirm again, plz

**Comment by thinkgos** [comment]
`runtime.SetFinalizer` don't work with circular references.  This is documented in the description of `runtime.SetFinalizer`.

`Finalizers are run in dependency order: if A points at B, both have finalizers, and they are otherwise unreachable, only the finalizer for A runs; once A is freed, the finalizer for B can run. If a cyclic structure includes a block with a finalizer, that cycle is not guaranteed to be garbage collected and the finalizer is not guaranteed to run, because there is no ordering that respects the dependencies.`

you should know golang use  tracing garbage collection.  how the golang garbage collection work. the golang  garbage collection can resolve circular references. But `runtime.SetFinalizer` can't, the doc  explain this.

in fact, Automatic Reference Counting can't resolve  circular references, So these languages ​​provide weak reference functions.

https://groups.google.com/g/golang-nuts/c/tzvgeBEW1WY
https://www.reddit.com/r/golang/comments/8jaqyw/circular_references
https://tip.golang.org/doc/gc-guide

**Comment by chgz** [comment]
Now, i see!
I applied for more memory in the closure and observed it for a long time, and it can indeed be GC!

And thanks for your explanation
